# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ComposeToIntellij < Formula
  desc "Command line application to convert Docker Compose environment variables to IntelliJ format."
  homepage "https://github.com/J-R-Oliver/homebrew-tools"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/J-R-Oliver/compose-to-intellij/releases/download/v1.0.0/compose-to-intellij_1.0.0_macOS_arm64.tar.gz"
      sha256 "46e29863048bdcd607ef18530e2e3d82df452d3f6573c73cb672004ab0f473b8"

      def install
        bin.install "compose-to-intellij"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/J-R-Oliver/compose-to-intellij/releases/download/v1.0.0/compose-to-intellij_1.0.0_macOS_x86_64.tar.gz"
      sha256 "161895b6b64032d3706c65bf4deaa8d36330110e7eaf66dbf9851d02d5abfd06"

      def install
        bin.install "compose-to-intellij"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/J-R-Oliver/compose-to-intellij/releases/download/v1.0.0/compose-to-intellij_1.0.0_Linux_arm64.tar.gz"
      sha256 "edf935c1c3732fe562f5fb706d7680aed8c6b2a397a895fc800b91da607aad4a"

      def install
        bin.install "compose-to-intellij"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/J-R-Oliver/compose-to-intellij/releases/download/v1.0.0/compose-to-intellij_1.0.0_Linux_x86_64.tar.gz"
      sha256 "6d43d5798ca86f6a32ca4e921f440b7625e3e5d6a2896ff682d017b76f93eff0"

      def install
        bin.install "compose-to-intellij"
      end
    end
  end
end
