# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ComposeToIntellij < Formula
  desc "Command-line application to convert Docker Compose env vars to IntelliJ format"
  homepage "https://github.com/J-R-Oliver/homebrew-tools"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/J-R-Oliver/compose-to-intellij/releases/download/v1.0.0/compose-to-intellij_1.0.0_macOS_arm64.tar.gz"
      sha256 "479e7267611a8c4cf5fce17e41f745f9e0f4ad8141b88de9ef776b05fbfc0c18"

      def install
        bin.install "compose-to-intellij"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/J-R-Oliver/compose-to-intellij/releases/download/v1.0.0/compose-to-intellij_1.0.0_macOS_x86_64.tar.gz"
      sha256 "9e60ff0c208369ea30a580ed7e32a0eb1386fb18b24566c3524fdcc02c88d66e"

      def install
        bin.install "compose-to-intellij"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/J-R-Oliver/compose-to-intellij/releases/download/v1.0.0/compose-to-intellij_1.0.0_Linux_arm64.tar.gz"
      sha256 "a3cdb3cfe77031e704b86ba7276c5b2721c4465c160378b600dfa7fd1c4f5637"

      def install
        bin.install "compose-to-intellij"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/J-R-Oliver/compose-to-intellij/releases/download/v1.0.0/compose-to-intellij_1.0.0_Linux_x86_64.tar.gz"
      sha256 "ec5e14456d56d5de01c55292e4859bfcc577ecd16c22f0e25e81040d7d9313b6"

      def install
        bin.install "compose-to-intellij"
      end
    end
  end
end
