# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ComposeToIntellij < Formula
  desc ""
  homepage "https://github.com/J-R-Oliver/homebrew-tools"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/J-R-Oliver/compose-to-intellij/releases/download/v1.0.0/compose-to-intellij_1.0.0_macOS_x86_64.tar.gz"
      sha256 "1d646daca48a8064efa848bda4b5ba59d1ebfb63228a176666e3fb0256aa98c3"

      def install
        bin.install "compose-to-intellij"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/J-R-Oliver/compose-to-intellij/releases/download/v1.0.0/compose-to-intellij_1.0.0_macOS_arm64.tar.gz"
      sha256 "5e904970478c75e9ac32f94e5cada56877020510a0617f83c3c8ad7bcb1e9511"

      def install
        bin.install "compose-to-intellij"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/J-R-Oliver/compose-to-intellij/releases/download/v1.0.0/compose-to-intellij_1.0.0_Linux_arm64.tar.gz"
      sha256 "48b3397b8a505b7d021b34d5fe0f8e3b36dbefce24446f5b9bdbf8d290406b64"

      def install
        bin.install "compose-to-intellij"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/J-R-Oliver/compose-to-intellij/releases/download/v1.0.0/compose-to-intellij_1.0.0_Linux_x86_64.tar.gz"
      sha256 "51a3df83ffae3d5434e90fb2d7bb185795aeb24d869e893ec44aeeb3e73942ee"

      def install
        bin.install "compose-to-intellij"
      end
    end
  end
end
