# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ComposeToIntellij < Formula
  desc "Command-line application to convert Docker Compose env vars to IntelliJ format"
  homepage "https://github.com/J-R-Oliver/homebrew-tools"
  version "1.0.0"
  license "UNLICENSE"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/J-R-Oliver/compose-to-intellij/releases/download/v1.0.0/compose-to-intellij_1.0.0_macOS_arm64.tar.gz"
      sha256 "19706e248aa6162726d7e74a2b11c8b98526094b78506ef2c7c4b9f1cc87bd59"

      def install
        bin.install "compose-to-intellij"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/J-R-Oliver/compose-to-intellij/releases/download/v1.0.0/compose-to-intellij_1.0.0_macOS_x86_64.tar.gz"
      sha256 "84ab5e63be050af21a64836ba253704f3449d046cc05a0cd3893d178b9713e4f"

      def install
        bin.install "compose-to-intellij"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/J-R-Oliver/compose-to-intellij/releases/download/v1.0.0/compose-to-intellij_1.0.0_Linux_arm64.tar.gz"
      sha256 "60a17c825b93ae2ccb6e5d0948062a31a65858e43ad30943d8e0a5a04f9b5925"

      def install
        bin.install "compose-to-intellij"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/J-R-Oliver/compose-to-intellij/releases/download/v1.0.0/compose-to-intellij_1.0.0_Linux_x86_64.tar.gz"
      sha256 "e5a3a624fac96003d91523f4e4bb39e493c492432a121bd8bdaa499bdb383ea0"

      def install
        bin.install "compose-to-intellij"
      end
    end
  end
end
