# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ComposeToIntellij < Formula
  desc "Command-line application to convert Docker Compose env vars to IntelliJ format"
  homepage "https://github.com/J-R-Oliver/homebrew-tools"
  version "1.0.0"
  license "Unlicense"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/J-R-Oliver/compose-to-intellij/releases/download/v1.0.0/compose-to-intellij_1.0.0_macOS_arm64.tar.gz"
      sha256 "8082cee703970324a049e3526883563592df473d086a8e890080db19c1c1a98a"

      def install
        bin.install "compose-to-intellij"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/J-R-Oliver/compose-to-intellij/releases/download/v1.0.0/compose-to-intellij_1.0.0_macOS_x86_64.tar.gz"
      sha256 "3eaa1f8d1d8a2fea5f02e73f647a50f43c5f3a2fab6af41ee79df39276ed2985"

      def install
        bin.install "compose-to-intellij"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/J-R-Oliver/compose-to-intellij/releases/download/v1.0.0/compose-to-intellij_1.0.0_Linux_x86_64.tar.gz"
      sha256 "922fb13d65d66325c4bf81dc16158c007b53d7a353fefead3937289c57ba063c"

      def install
        bin.install "compose-to-intellij"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/J-R-Oliver/compose-to-intellij/releases/download/v1.0.0/compose-to-intellij_1.0.0_Linux_arm64.tar.gz"
      sha256 "592f597d4f7fbd1ca07b8d19bb89a09bc6e10bb2a5b21489fc736e62083b27fb"

      def install
        bin.install "compose-to-intellij"
      end
    end
  end
end
