# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ComposeToIntellij < Formula
  desc "Command-line application to convert Docker Compose env vars to IntelliJ format"
  homepage "https://github.com/J-R-Oliver/homebrew-tools"
  version "1.0.0"
  license "Unlicense"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/J-R-Oliver/compose-to-intellij/releases/download/v1.0.0/compose-to-intellij_1.0.0_macOS_arm64.tar.gz"
      sha256 "0b9dd1a0f4e019da93080896a669b73107812602cba11792c1d5ab8dcc4ad78b"

      def install
        bin.install "compose-to-intellij"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/J-R-Oliver/compose-to-intellij/releases/download/v1.0.0/compose-to-intellij_1.0.0_macOS_x86_64.tar.gz"
      sha256 "73a62b14e01640a6ef359e2742f255cd25844a0f665910ef1f6670de03663171"

      def install
        bin.install "compose-to-intellij"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/J-R-Oliver/compose-to-intellij/releases/download/v1.0.0/compose-to-intellij_1.0.0_Linux_arm64.tar.gz"
      sha256 "065104056410d22ef24f0a8c5590df580d007485d4bf9facf7d35c49b4e878da"

      def install
        bin.install "compose-to-intellij"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/J-R-Oliver/compose-to-intellij/releases/download/v1.0.0/compose-to-intellij_1.0.0_Linux_x86_64.tar.gz"
      sha256 "afacdd1f441b8c89dbbdfed12db72eec5d33a0c0a046276a9f1b4efec1c74852"

      def install
        bin.install "compose-to-intellij"
      end
    end
  end
end
